name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.lhci.outputs.MANIFEST }}
    steps:
      - uses: actions/checkout@v3
      - name: Lighthouse
        id: lhci
        uses: shopify/lighthouse-ci-action@fd074fead4a64d4aa90254889c0eec0b14c9de17
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
          lhci_output_json: true
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    needs: [lhci]
    steps:
      - env:
          INPUT: ${{needs.lchi.outputs.MANIFEST}}
        run: echo "$INPUT"
